background = #181825
base = #1e1e2e
text = #bac2de
bright_text = #cdd6f4
accent = #b4befe
accent_secondary = #f38ba8

h1_size = 24
h2_size = 18
h3_size = 14
font_size = 12
small_font_size = 10

font_family = "JetBrains Mono"
font_family_monospace = "JetBrains Mono"

icon-theme = "Papirus"
