# ╔═════════════════════════════════════════════════╗
# ║ KEYWORDS CONFIGURATION                          ║
# ║ https://wiki.hyprland.org/Configuring/Keywords/ ║
# ╚═════════════════════════════════════════════════╝

# Set main modifier key.
$mainMod = SUPER

$terminal = ghostty
$fileManager = $terminal -e lf
$menu = rofi -show drun
